export default [
  {
    title: 'Pojazdy lądowe',
    images: [
      {
        image: require('./vehicles-land/car.png'),
        description: 'Samochód',
        facts: [
          'Samochód ma zwykle cztery koła.',
          'Samochód przewozi ludzi i ich rzeczy.',
          'Większość samochodów ma silnik zasilany paliwem lub prądem.',
          'Samochody mają światła, które pomagają widzieć nocą.',
          'Kierowcy muszą przestrzegać zasad ruchu drogowego.',
        ],
      },
      {
        image: require('./vehicles-land/bus.png'),
        description: 'Autobus',
        facts: [
          'Autobus przewozi wiele osób jednocześnie.',
          'Autobusy zatrzymują się na przystankach, by wsiadali pasażerowie.',
          'Niektóre autobusy są zasilane paliwem, inne prądem elektrycznym.',
          'W autobusie trzeba ustępować miejsca starszym i chorym.',
          'Autobusy pomagają zmniejszać liczbę samochodów w mieście.',
        ],
      },
      {
        image: require('./vehicles-land/train.png'),
        description: 'Pociąg',
        facts: [
          'Pociąg jedzie po torach stalowych.',
          'Pociągi przewożą ludzi i towary na długie dystanse.',
          'Pociąg ma lokomotywę, która ciągnie wagony.',
          'Stacje kolejowe to miejsca, gdzie pociągi zatrzymują się.',
          'Niektóre pociągi są bardzo szybkie i nazywa się je ekspresami.',
        ],
      },
      {
        image: require('./vehicles-land/tram.png'),
        description: 'Tramwaj',
        facts: [
          'Tramwaj jeździ po szynach w mieście.',
          'Zasilany jest zwykle prądem z sieci trakcyjnej.',
          'Tramwaje zatrzymują się na przystankach ulicznych.',
          'W tramwaju są siedzenia i miejsca stojące dla pasażerów.',
          'Tramwaje pomagają przewozić ludzi po mieście.',
        ],
      },
      {
        image: require('./vehicles-land/bicycle.png'),
        description: 'Rower',
        facts: [
          'Rower ma dwa koła.',
          'Rower napędza się pedałami.',
          'Noszenie kasku chroni głowę podczas jazdy.',
          'Rower ma hamulce, żeby bezpiecznie się zatrzymać.',
          'Jazda na rowerze to zdrowe ćwiczenie dla dzieci.',
        ],
      },
      {
        image: require('./vehicles-land/motorcycle.png'),
        description: 'Motocykl',
        facts: [
          'Motocykl ma zwykle dwa koła.',
          'Porusza się dzięki silnikowi spalinowemu lub elektrycznemu.',
          'Jazda motocyklem jest szybsza niż na rowerze.',
          'Kask i ubranie ochronne zwiększają bezpieczeństwo motocyklisty.',
          'Motocykle mają światła i lusterka, by dobrze widzieć i być widocznym.',
        ],
      },
      {
        image: require('./vehicles-land/tractor.png'),
        description: 'Traktor',
        facts: [
          'Traktor pracuje na polu i pomaga rolnikom.',
          'Ma mocny silnik i duże ogumione koła.',
          'Traktor ciągnie maszyny i przyczepy z ładunkiem.',
          'Służy do orki, siania i zbiorów na polu.',
          'Traktory często poruszają się wolniej niż samochody.',
        ],
      },
      {
        image: require('./vehicles-land/fire-truck.png'),
        description: 'Wóz strażacki',
        facts: [
          'Wóz strażacki przewozi strażaków i sprzęt ratunkowy.',
          'Ma drabinę, by sięgać wyżej w czasie akcji.',
          'Wóz strażacki ma syrenę i migające światła, by ostrzegać innych.',
          'Wyposażony jest w pompę do podawania wody na pożar.',
          'Strażacy używają wozu także do ratowania ludzi i zwierząt.',
        ],
      },
    ],
  },
  {
    title: 'Pojazdy powietrzne i wodne',
    images: [
      {
        image: require('./vehicles-air-water/airplane.png'),
        description: 'Samolot',
        facts: [
          'Samolot lata w powietrzu dzięki skrzydłom i silnikom.',
          'Pilot kontroluje samolot z kabiny na przedzie maszyny.',
          'Skrzydła samolotu pomagają mu wznosić się i opadać.',
          'Lotniska mają pasy startowe do startu i lądowania samolotów.',
          'Samoloty mogą latać wysoko nad chmurami, gdzie jest mniejszy opór powietrza.',
        ],
      },
      {
        image: require('./vehicles-air-water/helicopter.png'),
        description: 'Helikopter',
        facts: [
          'Helikopter unosi się dzięki obracającym się wirnikom.',
          'Może startować i lądować pionowo na małej przestrzeni.',
          'Pilot steruje wirnikami i kierunkiem lotu z kabiny.',
          'Helikoptery pomagają w ratowaniu ludzi i transporcie.',
          'Śmigła helikoptera mogą się obracać bardzo szybko.',
        ],
      },
      {
        image: require('./vehicles-air-water/sailboat.png'),
        description: 'Żaglówka',
        facts: [
          'Żaglówka płynie dzięki wiatrowi, który napina żagle.',
          'Kapitan steruje kierunkiem za pomocą steru.',
          'Żagle mają różne kształty i pomagają łodzi poruszać się.',
          'Wiatr i fale wpływają na szybkość żaglówki.',
          'Na żaglówce trzeba znać zasady bezpieczeństwa i nosić kamizelkę.',
        ],
      },
      {
        image: require('./vehicles-air-water/ship.png'),
        description: 'Statek',
        facts: [
          'Statek może przewozić ludzi lub towary po morzu.',
          'Duże statki mają wiele pokładów i kabin.',
          'Kapitan dowodzi statkiem i dba o bezpieczeństwo załogi.',
          'Statki używają silników lub żagli do poruszania się.',
          'Na statku ważne są mapy i urządzenia nawigacyjne.',
        ],
      },
      {
        image: require('./vehicles-air-water/submarine.png'),
        description: 'Okręt podwodny',
        facts: [
          'Okręt podwodny pływa pod wodą i wynurza się na powierzchnię.',
          'Zabiera załogę i sprzęt do badań lub misji.',
          'Do zmiany głębokości używa balastu, który napełnia się wodą.',
          'Okręty podwodne mają okrągłe kadłuby, żeby wytrzymać ciśnienie.',
          'W środku są peryskopy i instrumenty do obserwacji z zewnątrz.',
        ],
      },
      {
        image: require('./vehicles-air-water/hot-air-balloon.png'),
        description: 'Balon',
        facts: [
          'Balon unosi się dzięki gorącemu powietrzu w dużym płótnie.',
          'Pasażerowie siedzą w koszu pod dużym balonem.',
          'Pilot grzeje powietrze palnikiem, aby balon się wzniósł.',
          'Latem i przy dobrej pogodzie robi się loty balonem.',
          'Balony poruszają się z wiatrem i trudno nimi mocno kierować.',
        ],
      },
      {
        image: require('./vehicles-air-water/rocket.png'),
        description: 'Rakieta',
        facts: [
          'Rakieta leci w kosmos dzięki silnym silnikom i paliwu.',
          'Wynosi satelity, sondy lub ludzi na orbitę.',
          'Start rakiety wymaga dużo energii i precyzyjnego planu.',
          'Rakiety mają stopnie, które odrzucają się w locie.',
          'Astronauci noszą skafandry podczas wypraw kosmicznych.',
        ],
      },
      {
        image: require('./vehicles-air-water/kayak.png'),
        description: 'Kajak',
        facts: [
          'Kajak to mała łódka, którą wiosłuje się dwoma wiosłami.',
          'Jest lekki i popularny do zabawy na rzekach i jeziorach.',
          'Pływając kajakiem, zakłada się kamizelkę ratunkową dla bezpieczeństwa.',
          'Kajaki mają różne kształty do szybkiego lub spokojnego pływania.',
          'Dzieci pływają kajakiem z dorosłymi i pod nadzorem.',
        ],
      },
    ],
  },
  {
    title: 'Warzywa',
    images: [
      {
        image: require('./vegetables2/carrot.png'),
        description: 'Marchewka',
        facts: [
          'Marchewka jest pomarańczowa i chrupiąca.',
          'Rośnie w ziemi jako korzeń.',
          'Jest bogata w witaminę A.',
          'Można ją jeść na surowo i gotowaną.',
          'Pomaga dbać o zdrowe oczy.',
        ],
      },
      {
        image: require('./vegetables2/cucumber.png'),
        description: 'Ogórek',
        facts: [
          'Ogórek jest zielony i orzeźwiający.',
          'Składa się głównie z wody.',
          'Rośnie na pnączach lub krzaczkach.',
          'Można go jeść na surowo w sałatkach.',
          'Jest popularny w letnich kanapkach.',
        ],
      },
      {
        image: require('./vegetables2/tomato.png'),
        description: 'Pomidor',
        facts: [
          'Pomidor jest czerwony lub zielony.',
          'Należy do rodziny psiankowatych.',
          'Można go jeść na surowo i po ugotowaniu.',
          'Pomidory rosną na krzakach.',
          'Są używane do zupy i sosu.',
        ],
      },
      {
        image: require('./vegetables2/potato.png'),
        description: 'Ziemniak',
        facts: [
          'Ziemniak rośnie pod ziemią jako bulwa.',
          'Można go piec, gotować i smażyć.',
          'Zawiera skrobię, która daje energię.',
          'Roślina ma liście i kwiaty nad ziemią.',
          'Ziemniaki były ważnym pożywieniem w wielu krajach.',
        ],
      },
      {
        image: require('./vegetables2/broccoli.png'),
        description: 'Brokuł',
        facts: [
          'Brokuł ma zielone różyczki przypominające drzewo.',
          'Jest bogaty w witaminy i błonnik.',
          'Można go jeść surowy lub gotowany.',
          'Rośnie nad ziemią na łodydze.',
          'Często pojawia się w zdrowych obiadach.',
        ],
      },
      {
        image: require('./vegetables2/pepper.png'),
        description: 'Papryka',
        facts: [
          'Papryka może być kolorowa i słodka.',
          'Rośnie na krzewach i ma nasiona w środku.',
          'Zawiera witaminę C, ważną dla zdrowia.',
          'Można ją jeść na surowo lub piec.',
          'Papryka bywa łagodna lub ostra.',
        ],
      },
      {
        image: require('./vegetables2/onion.png'),
        description: 'Cebula',
        facts: [
          'Cebula ma warstwy i ostry smak.',
          'Cebula rośnie jako cebulka pod ziemią.',
          'Krojenie cebuli może powodować łzy.',
          'Cebula dodaje smaku wielu potrawom.',
          'Jest bogata w witaminy i minerały.',
        ],
      },
      {
        image: require('./vegetables2/pumpkin.png'),
        description: 'Dynia',
        facts: [
          'Dynia jest duża i ma twardą skórę.',
          'W środku ma nasiona i miąższ.',
          'Można z niej robić zupy i ciasta.',
          'Na Halloween wydrąża się dynie i robi lampiony.',
          'Dynia rośnie na płożących się pędach.',
        ],
      },
    ],
  },
  {
    title: 'Ptaki',
    images: [
      {
        image: require('./birds/eagle.png'),
        description: 'Orzeł',
        facts: [
          'Orzeł to duży ptak drapieżny z silnymi pazurami i zakrzywionym dziobem.',
          'Ma bardzo dobry wzrok i potrafi wypatrzyć ofiarę z dużej wysokości.',
          'Orły budują duże gniazda zwane lęgowiskami na skałach lub drzewach.',
          'Żywią się mięsem, jedzą ryby, małe ssaki i ptaki.',
          'Niektóre gatunki orłów są wędrowne i pokonują długie trasy.',
        ],
      },
      {
        image: require('./birds/owl.png'),
        description: 'Sowa',
        facts: [
          'Sowa to nocny ptak z dużymi oczami i cichym lotem.',
          'Potrafi obrócić głowę niemal dookoła, by lepiej widzieć.',
          'Ma pióra przystosowane do niemego lotu, dzięki czemu poluje cicho.',
          'Sowy jedzą głównie małe zwierzęta, np. myszy i owady.',
          'Młode sowy uczą się polować od rodziców.',
        ],
      },
      {
        image: require('./birds/sparrow.png'),
        description: 'Wróbel',
        facts: [
          'Wróbel to mały ptak często spotykany w miastach i na wsiach.',
          'Lubi jeść ziarna i owady, które znajdzie na ziemi.',
          'Buduje gniazda z trawy i piórek w szczelinach budynków.',
          'Wróble są towarzyskie i często gromadzą się w małe stada.',
          'Samce często śpiewają, by przyciągnąć samice.',
        ],
      },
      {
        image: require('./birds/stork.png'),
        description: 'Bocian',
        facts: [
          'Bocian to duży ptak z długimi nogami i długim dziobem.',
          'Ptaki te często wracają do tych samych gniazd co roku.',
          'Bociany zwykle jedzą żaby, ryby i owady z pól i stawów.',
          'Wędrują na duże odległości podczas zmian pór roku.',
          'Budują duże gniazda z patyków na kominach i drzewach.',
        ],
      },
      {
        image: require('./birds/duck.png'),
        description: 'Kaczka',
        facts: [
          'Kaczka to ptak wodny z błoniastymi stopami do pływania.',
          'Ma pióra odporne na wodę dzięki specjalnemu olejowi.',
          'Kaczki pływają i nurkują, by szukać jedzenia.',
          'Kaczki mówią "kwaczą", to ich charakterystyczny dźwięk.',
          'Młode kaczki często idą za mamą tuż po wykluciu.',
        ],
      },
      {
        image: require('./birds/swan.png'),
        description: 'Łabędź',
        facts: [
          'Łabędź to duży ptak wodny o długiej szyi i białych piórach.',
          'Często pływa elegancko i wygląda bardzo dostojnie.',
          'Łabędzie mają błoniaste stopy, które pomagają wiosłować.',
          'Tworzą trwałe pary i razem opiekują się pisklętami.',
          'Jedzą rośliny wodne, czasem owady i małe ryby.',
        ],
      },
      {
        image: require('./birds/penguin.png'),
        description: 'Pingwin',
        facts: [
          'Pingwin to ptak, który nie lata, ale świetnie pływa.',
          'Ma krótkie skrzydła zamienione na płetwy do pływania.',
          'Żyje głównie na półkuli południowej, np. na Antarktydzie.',
          'Jego pióra utrzymują ciepło podczas zimnych kąpieli morskich.',
          'Pingwiny jedzą ryby, kryl i morskie bezkręgowce.',
        ],
      },
      {
        image: require('./birds/woodpecker.png'),
        description: 'Dzięcioł',
        facts: [
          'Dzięcioł dobija dziobem w drzewo, by szukać owadów.',
          'Ma mocny dziób i specjalne łapy do przytrzymywania się.',
          'Jego język może sięgać głęboko, by wyciągać larwy.',
          'Dzięcioły wybierają dziuple w drzewach na gniazda.',
          'Stukanie dzięcioła służy też do oznaczania terytorium i komunikacji.',
        ],
      },
    ],
  },
  {
    title: 'Instrumenty muzyczne',
    images: [
      {
        image: require('./instruments/piano.png'),
        description: 'Fortepian',
        facts: [
          'Fortepian ma klawisze, które naciskamy palcami.',
          'Dźwięk powstaje przez uderzenie młoteczka w strunę.',
          'Fortepian może mieć wiele oktaw.',
          'Uczymy się na nim nut i rytmu.',
          'Jest używany w muzyce klasycznej i popularnej.',
        ],
      },
      {
        image: require('./instruments/guitar.png'),
        description: 'Gitara',
        facts: [
          'Gitara ma sześć strun, które szarpiemy palcami.',
          'Dźwięk zmienia się przez nacisk na progi.',
          'Akordy tworzy się grając kilka strun razem.',
          'Gitara może być akustyczna lub elektryczna.',
          'Jest popularna w muzyce folk i rock.',
        ],
      },
      {
        image: require('./instruments/violin.png'),
        description: 'Skrzypce',
        facts: [
          'Skrzypce mają cztery struny.',
          'Gramy na nich smyczkiem przesuwanym po strunach.',
          'Mają mały kształt i długi gryf.',
          'Są ważne w orkiestrze symfonicznej.',
          'Dzieci uczą się pozycji palców i dźwięków.',
        ],
      },
      {
        image: require('./instruments/drums.png'),
        description: 'Perkusja',
        facts: [
          'Perkusja to zestaw bębnów i talerzy.',
          'Gramy pałeczkami lub rękami, by stworzyć rytm.',
          'Perkusista utrzymuje tempo całej piosenki.',
          'Istnieją różne rodzaje bębnów, małe i duże.',
          'Perkusja jest ważna w muzyce rozrywkowej i jazzowej.',
        ],
      },
      {
        image: require('./instruments/flute.png'),
        description: 'Flet',
        facts: [
          'Flet jest długą rurką z otworami.',
          'Dźwięk powstaje przez dmuchnięcie w otwór ustny.',
          'Zakrywając otwory palcami zmieniamy dźwięki.',
          'Flet występuje w orkiestrze i muzyce kameralnej.',
          'Jest lekki i często srebrny lub metalowy.',
        ],
      },
      {
        image: require('./instruments/trumpet.png'),
        description: 'Trąbka',
        facts: [
          'Trąbka ma metalowy kształt i ciekawy dźwięk.',
          'Dźwięk robi się przez wibrowanie ust na ustniku.',
          'Ma zawory, które zmieniają długość rury i dźwięk.',
          'Jest popularna w orkiestrach i zespołach jazzowych.',
          'Naukę zaczyna się od prostych melodii i ćwiczeń oddechu.',
        ],
      },
      {
        image: require('./instruments/saxophone.png'),
        description: 'Saksofon',
        facts: [
          'Saksofon jest zrobiony z metalu i ma ustnik.',
          'Dźwięk powstaje przez stroik drgający w ustniku.',
          'Ma klawisze, które zakrywają otwory, by zmieniać dźwięk.',
          'Jest często używany w jazzie i muzyce rozrywkowej.',
          'Występuje w różnych rozmiarach, od sopranu do barytonu.',
        ],
      },
      {
        image: require('./instruments/accordion.png'),
        description: 'Akordeon',
        facts: [
          'Akordeon ma miech, klawisze i guziki.',
          'Dźwięk powstaje przez przesuwanie miecha powietrza przez stroiki.',
          'Gramy jedną ręką na klawiszach, drugą na guzikach bassowych.',
          'Jest popularny w muzyce ludowej wielu krajów.',
          'Można go nosić i grać stojąc lub siedząc.',
        ],
      },
    ],
  },
  {
    title: 'Zawody',
    images: [
      {
        image: require('./jobs/doctor.png'),
        description: 'Lekarz',
        facts: [
          'Lekarz pomaga ludziom wrócić do zdrowia.',
          'Lekarz bada pacjentów i słucha ich objawów.',
          'Lekarz może przepisać leki, które pomagają leczyć choroby.',
          'Lekarze używają stetoskopu, by słyszeć bicie serca.',
          'Lekarz dba też o profilaktykę i szczepienia.',
        ],
      },
      {
        image: require('./jobs/firefighter.png'),
        description: 'Strażak',
        facts: [
          'Strażak gasi pożary i ratuje ludzi z niebezpieczeństw.',
          'Strażacy używają wozów strażackich i węży z wodą.',
          'Strażak może wejść do płonącego budynku, by ratować życie.',
          'Strażacy ćwiczą codziennie, by być gotowymi do akcji.',
          'Strażak pomaga też przy wypadkach drogowych i powodzi.',
        ],
      },
      {
        image: require('./jobs/teacher.png'),
        description: 'Nauczyciel',
        facts: [
          'Nauczyciel uczy dzieci czytać, pisać i liczyć.',
          'Nauczyciel tłumaczy nowe rzeczy i zadaje zadania domowe.',
          'Nauczyciele organizują zabawy i zajęcia plastyczne.',
          'Nauczyciel pomaga dzieciom rozwiązywać konflikty i być życzliwym.',
          'Nauczyciele oceniają postępy i wspierają rozwój dzieci.',
        ],
      },
      {
        image: require('./jobs/police-officer.png'),
        description: 'Policjant',
        facts: [
          'Policjant pomaga utrzymać porządek i dbać o bezpieczeństwo.',
          'Policjant może kierować ruchem i pomagać przejść przez ulicę.',
          'Policjanci patrolują ulice, by zapobiegać przestępstwom.',
          'Policjant zbiera informacje i rozmawia ze świadkami.',
          'Policjant nosi odznakę i mundur, by być rozpoznawalny.',
        ],
      },
      {
        image: require('./jobs/chef.png'),
        description: 'Kucharz',
        facts: [
          'Kucharz przygotowuje posiłki, dbając o smak i bezpieczeństwo.',
          'Kucharz używa garnków, patelni i piekarnika.',
          'Kucharz myje owoce i warzywa przed gotowaniem.',
          'Kucharz mierzy składniki, by jedzenie było smaczne.',
          'Kucharz planuje menu i dba o zdrowe jedzenie.',
        ],
      },
      {
        image: require('./jobs/pilot.png'),
        description: 'Pilot',
        facts: [
          'Pilot steruje samolotem, by bezpiecznie przewieźć pasażerów.',
          'Pilot sprawdza pogodę i instrumenty przed startem.',
          'Pilot komunikuje się z kontrolą lotów podczas lotu.',
          'Piloci noszą uniformy i często noszą odznaki.',
          'Pilot uczył się długo, aby zdobyć licencję na latanie.',
        ],
      },
      {
        image: require('./jobs/farmer.png'),
        description: 'Rolnik',
        facts: [
          'Rolnik uprawia rośliny i hoduje zwierzęta na farmie.',
          'Rolnik podlewa pola i zbiera plony o odpowiedniej porze.',
          'Rolnik używa maszyn, by pracować szybciej na polu.',
          'Rolnik karmi zwierzęta i dba o ich zdrowie.',
          'Rolnik sprzedaje produkty, na przykład warzywa i jajka.',
        ],
      },
      {
        image: require('./jobs/astronaut.png'),
        description: 'Astronauta',
        facts: [
          'Astronauta lata w kosmos, by odkrywać inne planety i gwiazdy.',
          'Astronauta nosi skafander, który chroni przed brakiem powietrza.',
          'Astronauci ćwiczą i uczą się przez wiele lat.',
          'Na stacji kosmicznej jedzenie ma specjalne opakowania.',
          'W kosmosie astronauci unoszą się z powodu mikrograwitacji.',
        ],
      },
    ],
  },
  {
    title: 'Dinozaury',
    images: [
      {
        image: require('./dinosaurs/tyrannosaurus.png'),
        description: 'Tyranozaur',
        facts: [
          'Tyranozaur miał bardzo silne szczęki i ostre zęby.',
          'Tyranozaur chodził na dwóch mocnych nogach.',
          'Był jednym z największych drapieżników swoich czasów.',
          'Naukowcy odnajdują jego skamieniałości na różnych kontynentach.',
          'Miał bardzo krótkie ramiona w porównaniu do ciała.',
        ],
      },
      {
        image: require('./dinosaurs/triceratops.png'),
        description: 'Triceratops',
        facts: [
          'Triceratops miał trzy rogi i kościstą kryzę na szyi.',
          'Żył w późnej kredzie i mieszkał na terenach dzisiejszej Ameryki Północnej.',
          'Był roślinożerny i miał dziób do zrywania roślin.',
          'Chodził na czterech mocnych nogach.',
          'Mogły używać rogu i kryzy w obronie i komunikacji.',
        ],
      },
      {
        image: require('./dinosaurs/stegosaurus.png'),
        description: 'Stegozaur',
        facts: [
          'Stegozaur miał duże płytki kostne wzdłuż grzbietu.',
          'Na ogonie miał kolce zwane thagomizerem do obrony.',
          'Był roślinożerny i jadł niskie rośliny.',
          'Miał mały mózg w stosunku do wielkiego ciała.',
          'Płytki mogły pomagać w regulacji temperatury ciała.',
        ],
      },
      {
        image: require('./dinosaurs/brachiosaurus.png'),
        description: 'Brachiozaur',
        facts: [
          'Brachiozaur miał bardzo długą szyję i sięgał po liście wysoko.',
          'Był roślinożerny i jadł dużo roślin.',
          'Miał długie przednie nogi i krótsze tylne, więc grzbiet był skośny.',
          'Żył głównie w jurze miliony lat temu.',
          'Był jednym z najwyższych dinozaurów.',
        ],
      },
      {
        image: require('./dinosaurs/velociraptor.png'),
        description: 'Welociraptor',
        facts: [
          'Welociraptor był niewielki i miał pióra.',
          'Miał zakrzywiony pazur na stopie do chwytania ofiar.',
          'Żył w późnej kredzie na terenach dzisiejszej Azji.',
          'Był szybki i poruszał się na dwóch nogach.',
          'Naukowcy wciąż badają, czy polował w grupach.',
        ],
      },
      {
        image: require('./dinosaurs/ankylosaurus.png'),
        description: 'Ankylozaur',
        facts: [
          'Ankylozaur miał ciężką pancerzowatą zbroję z kości.',
          'Na końcu ogona miał twardą buławę do obrony.',
          'Był roślinożerny i chodził na czterech nogach.',
          'Jego pancerz chronił go przed drapieżnikami.',
          'Żył w późnej kredzie na terenach Ameryki Północnej.',
        ],
      },
      {
        image: require('./dinosaurs/diplodocus.png'),
        description: 'Diplodok',
        facts: [
          'Diplodok miał bardzo długą szyję i ogon.',
          'Był roślinożerny i zjadał liście z drzew.',
          'Miał smukłe ciało i chodził na czterech nogach.',
          'Żył w okresie jury miliony lat temu.',
          'Jego ogon mógł służyć do równowagi i obrony.',
        ],
      },
      {
        image: require('./dinosaurs/spinosaurus.png'),
        description: 'Spinozaur',
        facts: [
          'Spinozaur miał wysoki żagiel na grzbiecie.',
          'Miał długi pysk podobny do krokodyla, który pomagał łowić ryby.',
          'Prawdopodobnie spędzał dużo czasu w pobliżu wody.',
          'Był jednym z największych drapieżników swojej epoki.',
          'Naukowcy badają jego skamieniałości w Afryce Północnej.',
        ],
      },
    ],
  },
  {
    title: 'Sporty',
    images: [
      {
        image: require('./sports/football.png'),
        description: 'Piłka nożna',
        facts: [
          'W piłce nożnej gra się nogami, rzadko rękami.',
          'Celem jest wprowadzenie piłki do bramki przeciwnika.',
          'Mecz trwa zwykle dwa razy po czterdzieści pięć minut.',
          'Na boisku jest jeden sędzia główny i dwóch sędziów bocznych.',
          'Kluby mają różne kolory koszulek i własne nazwy.',
        ],
      },
      {
        image: require('./sports/basketball.png'),
        description: 'Koszykówka',
        facts: [
          'W koszykówce trzeba wrzucić piłkę do kosza ponad obręczą.',
          'Każda drużyna gra pięcioma zawodnikami na boisku.',
          'Rzuty za trzy punkty są wykonywane zza linii trzech punktów.',
          'Piłkę należy kozłować podczas biegu, inaczej sędzia zatrzyma grę.',
          'Mecze krótsze dla dzieci mają krótsze kwarty niż profesjonalne.',
        ],
      },
      {
        image: require('./sports/tennis.png'),
        description: 'Tenis',
        facts: [
          'Tenis gra się rakietą i piłką na korcie.',
          'Punkty liczy się jako 15, 30, 40 i gema.',
          'Serwuje zawodnik stojący za linią końcową.',
          'Kort może być trawiasty, ziemny lub twardy.',
          'W tenisie gra się pojedynczo lub w deblu z partnerem.',
        ],
      },
      {
        image: require('./sports/volleyball.png'),
        description: 'Siatkówka',
        facts: [
          'W siatkówce drużyny przepuszczają piłkę nad siatką.',
          'Na boisku gra sześciu zawodników z każdej drużyny.',
          'Piłka może być odbita trzy razy przed odesłaniem nad siatkę.',
          'Punkt zdobywa się, gdy przeciwnik nie odbije piłki.',
          'Mecz składa się z setów do określonej liczby punktów.',
        ],
      },
      {
        image: require('./sports/swimming.png'),
        description: 'Pływanie',
        facts: [
          'Pływanie to ruch w wodzie przy użyciu rąk i nóg.',
          'Istnieją różne style pływackie, na przykład kraul i żabka.',
          'Basen ma krawędzie i tory dla pływaków.',
          'Pływanie jest dobre dla całego ciała i zdrowia.',
          'Na basenie warto nosić czepki i okulary ochronne.',
        ],
      },
      {
        image: require('./sports/skiing.png'),
        description: 'Narciarstwo',
        facts: [
          'Narciarstwo jest sportem zimowym na śniegu, z nartami i kijkami.',
          'Trasy mają różne poziomy trudności oznaczone kolorami.',
          'Narty są przymocowane do butów za pomocą wiązań.',
          'Ważne jest noszenie kasku dla bezpieczeństwa na stoku.',
          'Narty pomagają ślizgać się po śniegu z kontrolą.',
        ],
      },
      {
        image: require('./sports/gymnastics.png'),
        description: 'Gimnastyka',
        facts: [
          'Gimnastyka rozwija siłę, gibkość i równowagę ciała.',
          'Ćwiczenia wykonywane są na macie, poręczach lub na drążku.',
          'Trener pomaga uczyć bezpiecznych ćwiczeń i technik.',
          'Rozgrzewka przed gimnastyką zmniejsza ryzyko kontuzji.',
          'Gimnastyka może być zabawą i sportem zawodowym.',
        ],
      },
      {
        image: require('./sports/athletics.png'),
        description: 'Lekkoatletyka',
        facts: [
          'Lekkoatletyka obejmuje biegi, skoki i rzuty.',
          'Biegi mają różne długości, od krótkich do długich.',
          'Skok w dal polega na dalekim skoku po wybiciu z rozbiegu.',
          'Rzuty obejmują rzut oszczepem, dyskiem lub kulą.',
          'Zawody lekkoatletyczne odbywają się na stadionie z torem.',
        ],
      },
    ],
  },
  {
    title: 'Zwierzęta morskie',
    images: [
      {
        image: require('./sea-animals/dolphin.png'),
        description: 'Delfin',
        facts: [
          'Delfiny to ssaki morskie, oddychają powietrzem przez otwór na głowie.',
          'Mają ostre zęby do chwytania ryb, nie do żucia.',
          'Komunikują się gwizdami i klikami.',
          'Żyją w stadach zwanych grupami społecznymi.',
          'Są bardzo zręczne i potrafią skakać nad wodą.',
        ],
      },
      {
        image: require('./sea-animals/whale.png'),
        description: 'Wieloryb',
        facts: [
          'Wieloryby to duże ssaki żyjące w oceanie.',
          'Niektóre wieloryby jedzą plankton i filtrują go przez fiszbiny.',
          'Oddychają powietrzem przez otwór oddechowy na głowie.',
          'Wydają dźwięki, które pomagają im się porozumiewać na duże odległości.',
          'Niektóre gatunki potrafią migrować na bardzo długie dystanse.',
        ],
      },
      {
        image: require('./sea-animals/shark.png'),
        description: 'Rekin',
        facts: [
          'Rekiny to ryby mające płetwy i szkielet zbudowany z chrząstki.',
          'Większość rekinów poluje na ryby i inne mniejsze zwierzęta.',
          'Mają bardzo dobry węch i wyczuwają krew w wodzie.',
          'Nie wszystkie rekiny są niebezpieczne dla ludzi.',
          'Niektóre rekiny, jak rekin wielorybi, jedzą plankton.',
        ],
      },
      {
        image: require('./sea-animals/octopus.png'),
        description: 'Ośmiornica',
        facts: [
          'Ośmiornica ma osiem ramion pokrytych przyssawkami.',
          'Potrafi zmieniać kolor i kształt ciała, aby się ukryć.',
          'Ma duży mózg i jest bardzo inteligentna.',
          'Potrafi wypuszczać atrament, żeby uciec przed drapieżnikiem.',
          'Żyje na dnie morza w skalnych szczelinach i jamach.',
        ],
      },
      {
        image: require('./sea-animals/sea-turtle.png'),
        description: 'Żółw morski',
        facts: [
          'Żółwie morskie mają twardą skorupę zwaną pancerzem.',
          'Oddychają powietrzem, dlatego muszą wychodzić na powierzchnię.',
          'Samice często wracają na tę samą plażę, by składać jaja.',
          'Młode żółwie idą od razu do wody po wykluciu.',
          'Żywią się roślinami i małymi zwierzętami morskimi.',
        ],
      },
      {
        image: require('./sea-animals/seahorse.png'),
        description: 'Konik morski',
        facts: [
          'Konik morski ma pionową pozycję i ogon zwinięty.',
          'Samce noszą i wysiadują jaja w torbie lęgowej.',
          'Żywią się drobnymi skorupiakami i planktonem.',
          'Przyczepiają ogon do roślin, żeby się nie zdmuchnąć.',
          'Mają pancerzyk zamiast łusek.',
        ],
      },
      {
        image: require('./sea-animals/jellyfish.png'),
        description: 'Meduza',
        facts: [
          'Meduzy mają galaretowate ciało i długie czułki.',
          'Niektóre meduzy mogą parzyć ludzi swoimi parzydełkami.',
          'Meduzy nie mają mózgu ani kości.',
          'Poruszają się wypychając wodę z ciała jak dzwon.',
          'Niektóre meduzy świecą w ciemności dzięki bioluminescencji.',
        ],
      },
      {
        image: require('./sea-animals/crab.png'),
        description: 'Krab',
        facts: [
          'Kraby mają twardy pancerz i szczypce z przodu.',
          'Mogą chodzić na boki dzięki budowie nóg.',
          'Żywią się resztkami roślin i małymi zwierzętami.',
          'Niektóre kraby żyją na plaży, inne w głębinach.',
          'Kraby linieją, czyli zrzucają stary pancerz, gdy rosną.',
        ],
      },
    ],
  },
  {
    title: 'Kosmos',
    images: [
      {
        image: require('./space2/sun.png'),
        description: 'Słońce',
        facts: [
          'Słońce jest gwiazdą i centrum Układu Słonecznego.',
          'Słońce daje Ziemi światło i ciepło.',
          'Słońce składa się głównie z wodoru i helu.',
          'Powierzchnia Słońca ma około 5500 stopni Celsjusza.',
          'Ma około 4,6 miliarda lat.',
        ],
      },
      {
        image: require('./space2/moon.png'),
        description: 'Księżyc',
        facts: [
          'Księżyc jest naturalnym satelitą Ziemi.',
          'Księżyc nie ma gęstej atmosfery.',
          'Jego grawitacja powoduje pływy oceanów na Ziemi.',
          'Księżyc zmienia fazy w ciągu miesiąca.',
          'Pierwsi ludzie stanęli na Księżycu w 1969 roku.',
        ],
      },
      {
        image: require('./space2/earth.png'),
        description: 'Ziemia',
        facts: [
          'Ziemia jest trzecią planetą od Słońca.',
          'Ziemia ma życie i różnorodne ekosystemy.',
          'Atmosfera Ziemi zawiera głównie azot i tlen.',
          'Około 71% powierzchni Ziemi pokrywa woda.',
          'Ziemia obraca się, co powoduje dzień i noc.',
        ],
      },
      {
        image: require('./space2/mars.png'),
        description: 'Mars',
        facts: [
          'Mars bywa nazywany Czerwoną Planetą z powodu tlenków żelaza.',
          'Ma cienką atmosferę z dużą ilością dwutlenku węgla.',
          'Na Marsie jest największy znany wulkan, Olympus Mons.',
          'Mars ma dwie małe księżyce: Phobos i Deimos.',
          'Naukowcy wysyłają łaziki, by badać Marsa.',
        ],
      },
      {
        image: require('./space2/jupiter.png'),
        description: 'Jowisz',
        facts: [
          'Jowisz jest największą planetą Układu Słonecznego.',
          'Jowisz to gazowy olbrzym z wodoru i helu.',
          'Wielka Czerwona Plama to olbrzymi wir burzowy na Jowiszu.',
          'Jowisz ma wiele księżyców, wśród nich Io i Europa.',
          'Silna grawitacja Jowisza wpływa na trajektorie komet i asteroid.',
        ],
      },
      {
        image: require('./space2/saturn.png'),
        description: 'Saturn',
        facts: [
          'Saturn ma rozległe pierścienie z lodu i skał.',
          'To gazowy olbrzym podobny do Jowisza.',
          'Niektóre pierścienie są cienkie i przezroczyste.',
          'Saturn ma wiele księżyców, jednym z nich jest Tytan.',
          'Gęstość Saturna jest mniejsza niż gęstość wody.',
        ],
      },
      {
        image: require('./space2/comet.png'),
        description: 'Kometa',
        facts: [
          'Kometa to małe ciało lodowe i skalne krążące wokół Słońca.',
          'Zbliżając się do Słońca kometa tworzy jasny warkocz.',
          'Składa się z jądra, otoczki i ogona.',
          'Orbity komet często są silnie eliptyczne.',
          'Słynna kometa Halleya powraca co około 76 lat.',
        ],
      },
      {
        image: require('./space2/space-station.png'),
        description: 'Stacja kosmiczna',
        facts: [
          'Stacja kosmiczna krąży wokół Ziemi na niskiej orbicie.',
          'Astronauci mieszkają tam i prowadzą eksperymenty.',
          'Na stacji panuje stan nieważkości, czyli mikrograwitacja.',
          'Przykładem jest Międzynarodowa Stacja Kosmiczna w skrócie ISS.',
          'Stacje używane są do badań, obserwacji i testów technologii kosmicznych.',
        ],
      },
    ],
  },
];
