export default [
  {
    title: 'Zwierzęta',
    images: [
      {
        image: require('./animals1/boar.png'),
        description: 'Dzik',
        facts: [
          'Dzik potrafi biegać z prędkością do 40 km/h, aby uciec przed drapieżnikami.',
          'Samice dzika nazywane są lochami, a młode warchlakami.',
          'Dzik ma bardzo dobrze rozwinięty węch, którym wyczuwa pożywienie nawet pod ziemią.',
          'Jego ryj służy do rycia w ziemi w poszukiwaniu korzeni i larw.',
          'Dziki żyją w stadach zwanych watahami, prowadzonych przez najstarszą samicę.',
          'Dzik widzi w ograniczonym stopniu, dlatego polega głównie na słuchu i węchu.',
          'W okresie jesiennym dziki jedzą żołędzie, kasztany i orzechy, aby zgromadzić tłuszcz.',
          'Dzik potrafi dobrze pływać i bez trudu pokonuje rzeki.',
          'Samce dzika mają kły nazywane szablami, które rosną całe życie.',
          'Warchlaki mają prążkowane futerko, które maskuje je w lesie.',
        ],
      },
      {
        image: require('./animals1/bull.png'),
        description: 'Byk',
        facts: [
          'Byk to dorosły samiec krowy, często używany w hodowli.',
          'Ma silnie rozwinięte mięśnie karku, które pomagają dźwigać ciężką głowę.',
          'Byki wykorzystuje się w zaprzęgach i pracach polowych w wielu krajach.',
          'Ich rogi rosną przez całe życie i mają warstwowe przekroje.',
          'Byki przejawiają terytorialne zachowania, zwłaszcza w okresie godowym.',
          'Byki są wykorzystywane w kulturze ludowej jako symbol siły i wytrwałości.',
          'W wielu gospodarstwach byk pełni rolę reproduktora dla całego stada.',
          'Byki potrafią ważyć ponad 1000 kilogramów w zależności od rasy.',
          'Podczas upałów byki chłodzą się kąpaniem w wodzie lub tarzaniem w błocie.',
          'Byki mają silnie rozwinięty instynkt obrony stada przed zagrożeniem.',
        ],
      },
      {
        image: require('./animals1/fox.png'),
        description: 'Lis',
        facts: [
          'Lis pospolity potrafi polować zarówno w dzień, jak i w nocy.',
          'Ma doskonały słuch, dzięki któremu słyszy gryzonie pod śniegiem.',
          'Lisy komunikują się zapachem, zostawiając ślady moczu i kału.',
          'Ich ogon, zwany kitą, służy do utrzymywania równowagi i przykrywania się podczas snu.',
          'Lis potrafi wydać ponad 40 różnych dźwięków, aby porozumieć się z innymi.',
          'Lis ma poduszeczki na łapach, które wyciszają kroki podczas polowania.',
          'W zimie futro lisa staje się gęstsze i jaśniejsze.',
          'Lisy tworzą spiżarnie, w których zakopują nadmiar pożywienia.',
          'Młode lisy, zwane szczeniętami, uczą się polować przez zabawę.',
          'Lis potrafi wspinać się na niskie drzewa i płoty w poszukiwaniu jedzenia.',
        ],
      },
      {
        image: require('./animals1/monkey.png'),
        description: 'Małpa',
        facts: [
          'Małpy to ssaki naczelne, które żyją głównie w lasach tropikalnych.',
          'Wiele gatunków małp używa ogona do zachowania równowagi na gałęziach.',
          'Małpy potrafią używać narzędzi, na przykład kamieni do rozłupywania orzechów.',
          'Komunikują się gestami, mimiką oraz różnymi odgłosami.',
          'Małpy żyją w grupach, gdzie ważna jest hierarchia i wzajemna pielęgnacja futra.',
          'Małpy mają złożone relacje społeczne, w których ważne są więzi rodzinne.',
          'Dźwięki wydawane przez małpy mogą ostrzegać przed różnymi drapieżnikami.',
          'Niektóre gatunki małp potrafią rozpoznawać się w lustrze, co świadczy o samoświadomości.',
          'Małpy spędzają dużo czasu na pielęgnowaniu sierści swoich towarzyszy.',
          'W menu małp pojawiają się owoce, liście, owady, a niekiedy małe kręgowce.',
        ],
      },
      {
        image: require('./animals1/mouse.png'),
        description: 'Mysz',
        facts: [
          'Mysz domowa potrafi urodzić nawet 10 miotów w ciągu roku.',
          'Jej siekacze rosną przez całe życie i wymagają ciągłego ścierania.',
          'Myszy orientują się w przestrzeni dzięki wąsom, zwanym wibrysami.',
          'Mogą skakać w górę ponad 25 centymetrów, mimo niewielkich rozmiarów.',
          'Myszy są aktywne głównie nocą i mają dobry słuch.',
          'Myszy znakują teren zapachem, aby odnaleźć drogę powrotną do gniazda.',
          'Potrafią wspinać się po pionowych powierzchniach dzięki ostrym pazurom.',
          'Ulubionym schronieniem myszy są ciepłe, suche miejsca w pobliżu pożywienia.',
          'Myszy wydają ultradźwięki, których człowiek nie słyszy.',
          'W naturze myszy budują skomplikowane systemy tuneli pod ziemią.',
        ],
      },
      {
        image: require('./animals1/rhino.png'),
        description: 'Nosorożec',
        facts: [
          'Nosorożce mają grubą, ale wrażliwą skórę o grubości do 5 centymetrów.',
          'Ich rogi zbudowane są z keratyny, tej samej substancji co ludzkie paznokcie.',
          'Nosorożce potrafią rozpędzić się do 50 km/h na krótkim dystansie.',
          'Mają słaby wzrok, ale doskonały zmysł węchu i słuch.',
          'Nosorożce spędzają wiele czasu w błocie, aby chronić skórę przed słońcem i pasożytami.',
          'Nosorożce żywią się głównie trawami, gałązkami i liśćmi.',
          'Samice rodzą jedno młode co kilka lat, a opieka trwa ponad dwa lata.',
          'Nosorożce zaznaczają terytorium poprzez kopce z odchodów i moczu.',
          'Mimo masywnej budowy mają czułe uszy obracające się niezależnie.',
          'Kłusownictwo jest największym zagrożeniem dla dzikich populacji nosorożców.',
        ],
      },
      {
        image: require('./animals2/badger.png'),
        description: 'Borsuk',
        facts: [
          'Borsuk prowadzi nocny tryb życia i większość dnia spędza w norze.',
          'Jego nory, zwane borsuczarniami, mogą mieć wiele wejść i być używane przez pokolenia.',
          'Borsuk ma silne pazury, którymi kopie tunele i zdobywa pożywienie.',
          'Żywi się owadami, drobnymi kręgowcami oraz owocami.',
          'Borsuki potrafią zapadać w lekki sen zimowy, ograniczając aktywność.',
          'Borsuki często dzielą swoje nory z lisami lub królikami.',
          'Ich futro ma charakterystyczne czarno-białe pasy na głowie.',
          'Borsuki regularnie sprzątają nory, wynosząc resztki jedzenia na zewnątrz.',
          'Mogą gromadzić tłuszcz w ogonie jako zapas energii na zimę.',
          'Borsuki komunikują się chrząkaniem, syczeniem oraz pomrukami.',
        ],
      },
      {
        image: require('./animals2/frog.png'),
        description: 'Żaba',
        facts: [
          'Żaby oddychają przez płuca oraz wilgotną skórę.',
          'Ich język jest przyklejony z przodu pyska, co pozwala szybko chwytać owady.',
          'Żaby składają skrzek w wodzie, z którego rozwijają się kijanki.',
          'Skóra żaby wydziela substancje chroniące przed chorobami i drapieżnikami.',
          'Żaby potrafią wykonywać długie skoki dzięki silnym tylnym nogom.',
          'Żaby potrafią zmieniać kolor skóry, aby dopasować się do otoczenia.',
          'Błony między palcami ułatwiają pływanie i skakanie na mokrym podłożu.',
          'Niektóre gatunki żab zapadają w sen zimowy na dnie zbiorników wodnych.',
          'Żaby mają ruchomą gałkę oczną, która pomaga w połykaniu pokarmu.',
          'Ich krzyk służy do przyciągania partnerów i zaznaczania terytorium.',
        ],
      },
      {
        image: require('./animals2/hare.png'),
        description: 'Zając',
        facts: [
          'Zając szarak osiąga prędkość nawet 70 km/h podczas ucieczki.',
          'Ma duże uszy, które pomagają mu słyszeć drapieżniki i regulować temperaturę ciała.',
          'Zające nie budują nor, lecz odpoczywają w płytkich zagłębieniach zwanych kotlinkami.',
          'Ich młode rodzą się w pełni owłosione i z otwartymi oczami.',
          'Zające prowadzą nocny tryb życia i są roślinożerne.',
          'Zające mają oczy ustawione po bokach głowy, co daje szerokie pole widzenia.',
          'W razie zagrożenia potrafią długo biec z wysoką prędkością.',
          'Latem futro zająca jest brązowe, zimą może jaśnieć dla lepszego maskowania.',
          'Zające często zjadają miękkie gałązki i zioła rosnące na polanach.',
          'Podczas żerowania nasłuchują drapieżników, nie przestając przeżuwać.',
        ],
      },
      {
        image: require('./animals2/horse.png'),
        description: 'Koń',
        facts: [
          'Koń ma bardzo rozwinięty zmysł równowagi, który pomaga w szybkim galopie.',
          'Ich zęby rosną przez większość życia i ścierają się podczas jedzenia trawy.',
          'Konie komunikują się ciałem i wydając różne dźwięki, np. rżenie.',
          'Stado koni ma hierarchię, na czele której stoi klacz przewodniczka.',
          'Konie mogą spać zarówno leżąc, jak i stojąc dzięki specjalnej budowie stawów.',
          'Koń ma pamięć przestrzenną, która pozwala mu odnajdywać drogę do stajni.',
          'Serce konia bije wolniej niż u człowieka, ale pompuje więcej krwi na uderzenie.',
          'Końskie kopyta rosną nieustannie i wymagają regularnego werkowania.',
          'Konie rozpoznają emocje ludzi po głosie i mowie ciała.',
          'Żuchwa konia wykonuje ruchy boczne, aby rozdrobnić włókniste rośliny.',
        ],
      },
      {
        image: require('./animals2/polecat.png'),
        description: 'Fretka',
        facts: [
          'Fretka domowa jest udomowioną formą tchórza europejskiego.',
          'Ma długi, giętki kręgosłup, co pozwala jej przeciskać się przez wąskie przestrzenie.',
          'Fretki przesypiają nawet 18 godzin dziennie.',
          'Są mięsożerne i mają krótki układ pokarmowy.',
          'Fretki komunikują się energicznymi zabawami i charakterystycznymi odgłosami, tzw. doking.',
          'Fretki mają gruczoły zapachowe, którymi znaczą teren i komunikują się.',
          'Fretki lubią kopać tunele w miękkim podłożu podczas zabawy.',
          'Dieta fretki powinna zawierać dużo białka pochodzenia zwierzęcego.',
          'Samice fretek wchodzą w długą ruję, dlatego wymagają opieki weterynaryjnej.',
          'Fretki są z natury ciekawskie i potrafią wciskać się w najmniejsze szczeliny.',
        ],
      },
      {
        image: require('./animals2/wolf.png'),
        description: 'Wilk',
        facts: [
          'Wilki żyją w zorganizowanych watahach z wyraźną hierarchią.',
          'Potrafią przebiec ponad 50 kilometrów w ciągu doby w poszukiwaniu pożywienia.',
          'Wilki porozumiewają się wyciem, które pomaga utrzymać kontakt na duże odległości.',
          'Mają doskonały węch, pozwalający wyczuć ofiarę z kilku kilometrów.',
          'Wilki odgrywają ważną rolę w ekosystemie, regulując liczebność roślinożerców.',
          'Wilki polują zespołowo, wykorzystując strategię nękania ofiary.',
          'Każda wataha ma swoje terytorium oznaczone zapachem i wyciem.',
          'Wilcze młode uczą się polować poprzez obserwację dorosłych.',
          'Wilki posiadają silne więzi rodzinne i wspólnie opiekują się młodymi.',
          'W naturalnych warunkach wilki żyją średnio 6-8 lat.',
        ],
      },
    ],
  },
  {
    title: 'Zwierzęta i Tropy 1',
    images: [
      {
        image: require('./animals1/boar.png'),
        description: 'Dzik',
        facts: [
          'Dzik potrafi biegać z prędkością do 40 km/h, aby uciec przed drapieżnikami.',
          'Samice dzika nazywane są lochami, a młode warchlakami.',
          'Dzik ma bardzo dobrze rozwinięty węch, którym wyczuwa pożywienie nawet pod ziemią.',
          'Jego ryj służy do rycia w ziemi w poszukiwaniu korzeni i larw.',
          'Dziki żyją w stadach zwanych watahami, prowadzonych przez najstarszą samicę.',
          'Dzik widzi w ograniczonym stopniu, dlatego polega głównie na słuchu i węchu.',
          'W okresie jesiennym dziki jedzą żołędzie, kasztany i orzechy, aby zgromadzić tłuszcz.',
          'Dzik potrafi dobrze pływać i bez trudu pokonuje rzeki.',
          'Samce dzika mają kły nazywane szablami, które rosną całe życie.',
          'Warchlaki mają prążkowane futerko, które maskuje je w lesie.',
        ],
      },
      {
        image: require('./animals1/boar-track.png'),
        description: 'Trop dzika',
        facts: [
          'Trop dzika ma kształt sercowaty z wyraźnymi ostrogami po bokach.',
          'Odległość między śladami wskazuje na prędkość biegu zwierzęcia.',
          'Twarde racice pozostawiają głębokie odciski w miękkiej glebie.',
          'Ślady lochy są zwykle mniejsze niż odciski samca.',
          'Wokół tropów często widać rozryty grunt, gdzie dzik szukał pokarmu.',
          'Na piaszczystym podłożu trop dzika bywa rozmyty przez szerokie racice.',
          'Odciski bocznych raciczek, czyli zawietrznych, wskazują na szybki bieg.',
          'W świeżym śniegu trop dzika wygląda jak odwrócone serca.',
          'W pobliżu tropów można znaleźć rozkopane mrowiska i pniaki.',
          'Ślady dzika często tworzą równoległe ścieżki całej watahy.',
        ],
      },
      {
        image: require('./animals1/bull.png'),
        description: 'Byk',
        facts: [
          'Byk to dorosły samiec krowy, często używany w hodowli.',
          'Ma silnie rozwinięte mięśnie karku, które pomagają dźwigać ciężką głowę.',
          'Byki wykorzystuje się w zaprzęgach i pracach polowych w wielu krajach.',
          'Ich rogi rosną przez całe życie i mają warstwowe przekroje.',
          'Byki przejawiają terytorialne zachowania, zwłaszcza w okresie godowym.',
          'Byki są wykorzystywane w kulturze ludowej jako symbol siły i wytrwałości.',
          'W wielu gospodarstwach byk pełni rolę reproduktora dla całego stada.',
          'Byki potrafią ważyć ponad 1000 kilogramów w zależności od rasy.',
          'Podczas upałów byki chłodzą się kąpaniem w wodzie lub tarzaniem w błocie.',
          'Byki mają silnie rozwinięty instynkt obrony stada przed zagrożeniem.',
        ],
      },
      {
        image: require('./animals1/bull-track.png'),
        description: 'Trop byka',
        facts: [
          'Trop byka jest szeroki i masywny z zaokrąglonymi krawędziami.',
          'Głębokość śladu zależy od ciężaru zwierzęcia i rodzaju podłoża.',
          'W odciskach racic często pozostają resztki błota lub trawy.',
          'Parzyste racice tworzą dwa główne odciski oraz czasem małe piętki z tyłu.',
          'Regularny rozstaw tropów wskazuje na spokojny marsz stada.',
          'Na twardym gruncie trop byka pozostawia płytkie, ale rozległe odciski.',
          'Ślady podkutych byków mają ślady metalowych gwoździ w podkowie.',
          'Rozbudowane mięśnie powodują, że odciski tylnych nóg są głębsze.',
          'Trop byka można odróżnić od krowy po większej rozpiętości śladów.',
          'W błocie odciski często wypełniają się wodą, tworząc małe kałuże.',
        ],
      },
      {
        image: require('./animals1/fox.png'),
        description: 'Lis',
        facts: [
          'Lis pospolity potrafi polować zarówno w dzień, jak i w nocy.',
          'Ma doskonały słuch, dzięki któremu słyszy gryzonie pod śniegiem.',
          'Lisy komunikują się zapachem, zostawiając ślady moczu i kału.',
          'Ich ogon, zwany kitą, służy do utrzymywania równowagi i przykrywania się podczas snu.',
          'Lis potrafi wydać ponad 40 różnych dźwięków, aby porozumieć się z innymi.',
          'Lis ma poduszeczki na łapach, które wyciszają kroki podczas polowania.',
          'W zimie futro lisa staje się gęstsze i jaśniejsze.',
          'Lisy tworzą spiżarnie, w których zakopują nadmiar pożywienia.',
          'Młode lisy, zwane szczeniętami, uczą się polować przez zabawę.',
          'Lis potrafi wspinać się na niskie drzewa i płoty w poszukiwaniu jedzenia.',
        ],
      },
      {
        image: require('./animals1/fox-track.png'),
        description: 'Trop lisa',
        facts: [
          'Trop lisa przypomina wydłużone owalne odciski z widocznymi pazurami.',
          'Ślady układają się w prostej linii, co świadczy o energooszczędnym chodzie.',
          'W zimie trop lisa często przecina ślady gryzoni, na które poluje.',
          'Pazury w odcisku są cienkie i ostre, różniące się od psich tropów.',
          'Mała odległość między odciskami wskazuje na płynny trucht zwierzęcia.',
          'W głębokim śniegu trop lisa przybiera kształt tuneli połączonych skokami.',
          'Równa linia odcisków świadczy o ekonomicznym poruszaniu się po terenie.',
          'Odciski lisa są mniejsze od psich i mają węższy rozstaw palców.',
          'Na piasku delikatne włosy między palcami zostawiają subtelne wzory.',
          'Często obok tropu widać odciśniętą kitę, gdy lis zatrzymuje się i siada.',
        ],
      },
      {
        image: require('./animals1/monkey.png'),
        description: 'Małpa',
        facts: [
          'Małpy to ssaki naczelne, które żyją głównie w lasach tropikalnych.',
          'Wiele gatunków małp używa ogona do zachowania równowagi na gałęziach.',
          'Małpy potrafią używać narzędzi, na przykład kamieni do rozłupywania orzechów.',
          'Komunikują się gestami, mimiką oraz różnymi odgłosami.',
          'Małpy żyją w grupach, gdzie ważna jest hierarchia i wzajemna pielęgnacja futra.',
          'Małpy mają złożone relacje społeczne, w których ważne są więzi rodzinne.',
          'Dźwięki wydawane przez małpy mogą ostrzegać przed różnymi drapieżnikami.',
          'Niektóre gatunki małp potrafią rozpoznawać się w lustrze, co świadczy o samoświadomości.',
          'Małpy spędzają dużo czasu na pielęgnowaniu sierści swoich towarzyszy.',
          'W menu małp pojawiają się owoce, liście, owady, a niekiedy małe kręgowce.',
        ],
      },
      {
        image: require('./animals1/monkey-track.png'),
        description: 'Trop małpy',
        facts: [
          'Trop małpy pokazuje pięć palców dłoni z przeciwstawnym kciukiem.',
          'Odciski stóp mają długi, chwytny paluch skierowany do wewnątrz.',
          'Na miękkiej ziemi często widać ślady ogona lub przeciągniętej gałęzi.',
          'Tropy mogą występować na drzewach jako odciski w miękkiej korze.',
          'Nieregularne rozstawienie śladów świadczy o skokowym poruszaniu się.',
          'Ślady małp na ziemi są często nieregularne z powodu skakania bokiem.',
          'W tropikalnych lasach tropy szybko znikają przez opadające liście.',
          'Odciski dłoni mają wyraźne linie papilarne, widoczne w miękkim błocie.',
          'Na piasku widać ślady paznokci używanych do chwytania gałęzi.',
          'Małpy pozostawiają często odciski po przystankach, gdzie żerowały na owocach.',
        ],
      },
      {
        image: require('./animals1/mouse.png'),
        description: 'Mysz',
        facts: [
          'Mysz domowa potrafi urodzić nawet 10 miotów w ciągu roku.',
          'Jej siekacze rosną przez całe życie i wymagają ciągłego ścierania.',
          'Myszy orientują się w przestrzeni dzięki wąsom, zwanym wibrysami.',
          'Mogą skakać w górę ponad 25 centymetrów, mimo niewielkich rozmiarów.',
          'Myszy są aktywne głównie nocą i mają dobry słuch.',
          'Myszy znakują teren zapachem, aby odnaleźć drogę powrotną do gniazda.',
          'Potrafią wspinać się po pionowych powierzchniach dzięki ostrym pazurom.',
          'Ulubionym schronieniem myszy są ciepłe, suche miejsca w pobliżu pożywienia.',
          'Myszy wydają ultradźwięki, których człowiek nie słyszy.',
          'W naturze myszy budują skomplikowane systemy tuneli pod ziemią.',
        ],
      },
      {
        image: require('./animals1/mouse-track.png'),
        description: 'Trop myszy',
        facts: [
          'Trop myszy tworzą maleńkie odciski przednich i tylnych łap.',
          'Pomiędzy odciskami często widać ślad ogona przeciąganego po ziemi.',
          'Tylne łapki pozostawiają większy, wydłużony ślad niż przednie.',
          'Ślady myszy układają się w krótkie serie przerywane skokami.',
          'W śniegu tropy myszy szybko zanikają przez ciepło ich ciała.',
          'Na śniegu trop myszy tworzy charakterystyczną linię kropek i esów.',
          'Myszy często biegną przy ścianach, dlatego ślady układają się wzdłuż przeszkód.',
          'Na piasku widać odbite drobne pazurki na końcach palców.',
          'Ślady myszy w spiżarniach prowadzą zwykle do nagryzionych zapasów.',
          'W nocnej rosie tropy szybko się rozmywają, pozostawiając tylko ślad ogona.',
        ],
      },
      {
        image: require('./animals1/rhino.png'),
        description: 'Nosorożec',
        facts: [
          'Nosorożce mają grubą, ale wrażliwą skórę o grubości do 5 centymetrów.',
          'Ich rogi zbudowane są z keratyny, tej samej substancji co ludzkie paznokcie.',
          'Nosorożce potrafią rozpędzić się do 50 km/h na krótkim dystansie.',
          'Mają słaby wzrok, ale doskonały zmysł węchu i słuch.',
          'Nosorożce spędzają wiele czasu w błocie, aby chronić skórę przed słońcem i pasożytami.',
          'Nosorożce żywią się głównie trawami, gałązkami i liśćmi.',
          'Samice rodzą jedno młode co kilka lat, a opieka trwa ponad dwa lata.',
          'Nosorożce zaznaczają terytorium poprzez kopce z odchodów i moczu.',
          'Mimo masywnej budowy mają czułe uszy obracające się niezależnie.',
          'Kłusownictwo jest największym zagrożeniem dla dzikich populacji nosorożców.',
        ],
      },
      {
        image: require('./animals1/rhino-track.png'),
        description: 'Trop nosorożca',
        facts: [
          'Trop nosorożca jest ogromny i okrągły z trzema palcami.',
          'Głębokość odcisku może przekraczać kilka centymetrów w miękkiej ziemi.',
          'Ślady często pojawiają się w pobliżu wodopojów i błotnych kąpielisk.',
          'Przód stopy zostawia szerszy odcisk niż tył.',
          'Rozstaw tropów wskazuje na powolny, ale ciężki krok zwierzęcia.',
          'Świeży trop nosorożca może wypełniać się wodą po deszczu.',
          'Odciski palców mają grube krawędzie z odciśniętymi fałdami skóry.',
          'Ślady często prowadzą wzdłuż ustalonych ścieżek między wodą a żerowiskiem.',
          'Na suchym piasku tropy są mniej wyraźne, ale pozostawiają szerokie wgłębienia.',
          'Obok odcisków można znaleźć odrapane pnie, o które nosorożec ociera skórę.',
        ],
      },
    ],
  },
  {
    title: 'Zwierzęta i Tropy 2',
    images: [
      {
        image: require('./animals2/badger.png'),
        description: 'Borsuk',
        facts: [
          'Borsuk prowadzi nocny tryb życia i większość dnia spędza w norze.',
          'Jego nory, zwane borsuczarniami, mogą mieć wiele wejść i być używane przez pokolenia.',
          'Borsuk ma silne pazury, którymi kopie tunele i zdobywa pożywienie.',
          'Żywi się owadami, drobnymi kręgowcami oraz owocami.',
          'Borsuki potrafią zapadać w lekki sen zimowy, ograniczając aktywność.',
          'Borsuki często dzielą swoje nory z lisami lub królikami.',
          'Ich futro ma charakterystyczne czarno-białe pasy na głowie.',
          'Borsuki regularnie sprzątają nory, wynosząc resztki jedzenia na zewnątrz.',
          'Mogą gromadzić tłuszcz w ogonie jako zapas energii na zimę.',
          'Borsuki komunikują się chrząkaniem, syczeniem oraz pomrukami.',
        ],
      },
      {
        image: require('./animals2/badger-track.png'),
        description: 'Trop borsuka',
        facts: [
          'Trop borsuka jest szeroki z pięcioma palcami i dużymi pazurami.',
          'Przednie łapy zostawiają bardziej wachlarzowaty odcisk niż tylne.',
          'W miękkim podłożu widać zgrubienie wskazujące na poduszkę śródręcza.',
          'Ślady często prowadzą do wejść do rozbudowanych nor.',
          'Borsuki poruszają się stępem, więc odciski tworzą pary obok siebie.',
          'Ślady borsuka ustawiają się w rytmie: przednia łapa, potem tylna w to samo miejsce.',
          'Na twardej glebie widać charakterystyczne pazury wystające przed odcisk palców.',
          'Tropy prowadzą często wzdłuż żywopłotów i miedz, gdzie borsuk szuka owadów.',
          'Wchodząc do nory, borsuk zostawia wachlarzowate rozorane ziemie wokół wejścia.',
          'Zimą tropy mogą znikać, gdy borsuk ogranicza aktywność i rzadko wychodzi.',
        ],
      },
      {
        image: require('./animals2/frog.png'),
        description: 'Żaba',
        facts: [
          'Żaby oddychają przez płuca oraz wilgotną skórę.',
          'Ich język jest przyklejony z przodu pyska, co pozwala szybko chwytać owady.',
          'Żaby składają skrzek w wodzie, z którego rozwijają się kijanki.',
          'Skóra żaby wydziela substancje chroniące przed chorobami i drapieżnikami.',
          'Żaby potrafią wykonywać długie skoki dzięki silnym tylnym nogom.',
          'Żaby potrafią zmieniać kolor skóry, aby dopasować się do otoczenia.',
          'Błony między palcami ułatwiają pływanie i skakanie na mokrym podłożu.',
          'Niektóre gatunki żab zapadają w sen zimowy na dnie zbiorników wodnych.',
          'Żaby mają ruchomą gałkę oczną, która pomaga w połykaniu pokarmu.',
          'Ich krzyk służy do przyciągania partnerów i zaznaczania terytorium.',
        ],
      },
      {
        image: require('./animals2/frog-track.png'),
        description: 'Trop żaby',
        facts: [
          'Trop żaby to charakterystyczne odciski z długimi, rozczapierzonymi palcami.',
          'Skoki tworzą naprzemienne ślady: przednie łapy lądują przed tylnymi.',
          'Na błocie pozostają rowki po błoniastych błonach między palcami.',
          'Ślady często pojawiają się w pobliżu stawów i wilgotnych miejsc.',
          'Rozstaw śladów odzwierciedla długość skoku konkretnego gatunku.',
          'W kałużach tropy żaby tworzą rozpryski błota w kierunku skoku.',
          'Ślady tylnych nóg są znacznie dłuższe od przednich odcisków.',
          'Na wilgotnych liściach tropy pozostawiają śliskie, błyszczące ślady.',
          'Żaby lądują równocześnie na dwóch tylnych nogach, co widać w rozstawie.',
          'W nocy można dostrzec tropy żaby prowadzące do miejsc z dużą ilością owadów.',
        ],
      },
      {
        image: require('./animals2/hare.png'),
        description: 'Zając',
        facts: [
          'Zając szarak osiąga prędkość nawet 70 km/h podczas ucieczki.',
          'Ma duże uszy, które pomagają mu słyszeć drapieżniki i regulować temperaturę ciała.',
          'Zające nie budują nor, lecz odpoczywają w płytkich zagłębieniach zwanych kotlinkami.',
          'Ich młode rodzą się w pełni owłosione i z otwartymi oczami.',
          'Zające prowadzą nocny tryb życia i są roślinożerne.',
          'Zające mają oczy ustawione po bokach głowy, co daje szerokie pole widzenia.',
          'W razie zagrożenia potrafią długo biec z wysoką prędkością.',
          'Latem futro zająca jest brązowe, zimą może jaśnieć dla lepszego maskowania.',
          'Zające często zjadają miękkie gałązki i zioła rosnące na polanach.',
          'Podczas żerowania nasłuchują drapieżników, nie przestając przeżuwać.',
        ],
      },
      {
        image: require('./animals2/hare-track.png'),
        description: 'Trop zająca',
        facts: [
          'Trop zająca układa się w literę Y: dwie duże tylne łapy przed dwoma mniejszymi.',
          'Odciski tylnych łap są wydłużone i pokazują rozstawione palce.',
          'W śniegu ślady formują charakterystyczny wachlarz z przodu.',
          'Zając zmienia kierunek zygzakiem, co utrudnia pogoń drapieżnikom.',
          'Świeże tropy mają wyraźne, ostre krawędzie i widoczny puszysty odcisk futra.',
          'Tropy zająca skręcają nagle, aby zmylić drapieżnika podążającego za zapachem.',
          'Ślady tylnych łap bywają nachodzące na siebie, tworząc szeroką plamę.',
          'Na błotnistym gruncie widać odcisk sierści z tyłu stóp.',
          'Rozstaw tropów zwiększa się, gdy zając przyspiesza w galopie.',
          'W śniegu odcisk ogona pojawia się jako drobna dziurka tuż za tylnymi śladami.',
        ],
      },
      {
        image: require('./animals2/horse.png'),
        description: 'Koń',
        facts: [
          'Koń ma bardzo rozwinięty zmysł równowagi, który pomaga w szybkim galopie.',
          'Ich zęby rosną przez większość życia i ścierają się podczas jedzenia trawy.',
          'Konie komunikują się ciałem i wydając różne dźwięki, np. rżenie.',
          'Stado koni ma hierarchię, na czele której stoi klacz przewodniczka.',
          'Konie mogą spać zarówno leżąc, jak i stojąc dzięki specjalnej budowie stawów.',
          'Koń ma pamięć przestrzenną, która pozwala mu odnajdywać drogę do stajni.',
          'Serce konia bije wolniej niż u człowieka, ale pompuje więcej krwi na uderzenie.',
          'Końskie kopyta rosną nieustannie i wymagają regularnego werkowania.',
          'Konie rozpoznają emocje ludzi po głosie i mowie ciała.',
          'Żuchwa konia wykonuje ruchy boczne, aby rozdrobnić włókniste rośliny.',
        ],
      },
      {
        image: require('./animals2/horse-track.png'),
        description: 'Trop konia',
        facts: [
          'Trop konia ma kształt podkowy z otwartą częścią z tyłu.',
          'Na twardym podłożu widać często iskry i drobne odpryski kamieni.',
          'Ślady kopyt pozwalają ocenić tempo: stęp tworzy równomierne odstępy.',
          'Podkowa pozostawia charakterystyczne metalowe odgniecenia.',
          'Głębokość odcisku świadczy o wadze konia i rodzaju gleby.',
          'Ślady kopyt ustawione parami wskazują na klus lub galop.',
          'Na mokrej trawie trop konia zostawia ciemniejsze odbicie rogowej ściany kopyta.',
          'Podkute konie zostawiają odciski gwoździ widoczne na twardym podłożu.',
          'W miękkim gruncie środek kopyta może odcisnąć tzw. strzałkę.',
          'Odciski konia w rzece tworzą półokrągłe wgłębienia w dnie.',
        ],
      },
      {
        image: require('./animals2/polecat.png'),
        description: 'Fretka',
        facts: [
          'Fretka domowa jest udomowioną formą tchórza europejskiego.',
          'Ma długi, giętki kręgosłup, co pozwala jej przeciskać się przez wąskie przestrzenie.',
          'Fretki przesypiają nawet 18 godzin dziennie.',
          'Są mięsożerne i mają krótki układ pokarmowy.',
          'Fretki komunikują się energicznymi zabawami i charakterystycznymi odgłosami, tzw. doking.',
          'Fretki mają gruczoły zapachowe, którymi znaczą teren i komunikują się.',
          'Fretki lubią kopać tunele w miękkim podłożu podczas zabawy.',
          'Dieta fretki powinna zawierać dużo białka pochodzenia zwierzęcego.',
          'Samice fretek wchodzą w długą ruję, dlatego wymagają opieki weterynaryjnej.',
          'Fretki są z natury ciekawskie i potrafią wciskać się w najmniejsze szczeliny.',
        ],
      },
      {
        image: require('./animals2/polecat-track.png'),
        description: 'Trop fretki',
        facts: [
          'Trop fretki to małe odciski z pięcioma palcami i ostrymi pazurkami.',
          'Ślady układają się w serpentynę, odzwierciedlając zwinny chód.',
          'Na śniegu widać ślady ogona przeciąganego tuż obok łap.',
          'Fretki często poruszają się skokami, tworząc parzyste grupy odcisków.',
          'W pobliżu nor gryzoni tropy mogą nagle zanikać, gdy fretka wchodzi do środka.',
          'Trop fretki układa się w krótkie serie śladów zakończonych odpoczynkiem.',
          'W piasku widać odgniecione włoski między palcami łap fretki.',
          'Fretki zostawiają też ślady gryzienia na korzeniach w pobliżu tropów.',
          'Odciski tylnej łapy nachodzą na przednią, tworząc podwójny zarys.',
          'Tropy fretki często prowadzą do wody, gdzie poluje na ryby lub żaby.',
        ],
      },
      {
        image: require('./animals2/wolf.png'),
        description: 'Wilk',
        facts: [
          'Wilki żyją w zorganizowanych watahach z wyraźną hierarchią.',
          'Potrafią przebiec ponad 50 kilometrów w ciągu doby w poszukiwaniu pożywienia.',
          'Wilki porozumiewają się wyciem, które pomaga utrzymać kontakt na duże odległości.',
          'Mają doskonały węch, pozwalający wyczuć ofiarę z kilku kilometrów.',
          'Wilki odgrywają ważną rolę w ekosystemie, regulując liczebność roślinożerców.',
          'Wilki polują zespołowo, wykorzystując strategię nękania ofiary.',
          'Każda wataha ma swoje terytorium oznaczone zapachem i wyciem.',
          'Wilcze młode uczą się polować poprzez obserwację dorosłych.',
          'Wilki posiadają silne więzi rodzinne i wspólnie opiekują się młodymi.',
          'W naturalnych warunkach wilki żyją średnio 6-8 lat.',
        ],
      },
      {
        image: require('./animals2/wolf-track.png'),
        description: 'Trop wilka',
        facts: [
          'Trop wilka jest większy i bardziej owalny niż psa domowego.',
          'Przednie łapy zostawiają głębsze odciski przez większą masę ciała.',
          'Ślady ustawiają się w niemal prostej linii, oszczędzając energię.',
          'Palce są dłuższe i węższe, a pazury tworzą ostre zakończenia.',
          'Wataha może zostawiać równoległe ścieżki kilku osobników.',
          'W głębokim śniegu wilki poruszają się gęsiego, zostawiając pojedynczą linię śladów.',
          'Odciski wilka są symetryczne, co pomaga odróżnić je od psa domowego.',
          'Ślady pazurów są proste i ostre, świadcząc o twardych paznokciach.',
          'Wilki często oznaczają trasę moczem, co ułatwia identyfikację tropów.',
          'Wataha może rozdzielać się, tworząc rozwidlenia tropów w kilku kierunkach.',
        ],
      },
    ],
  },
  {
    title: 'Owoce',
    images: [
      {
        image: require('./fruits/apple.png'),
        description: 'Jabłko',
        facts: [
          'Jabłka zawierają pektyny, które wspierają pracę układu trawiennego.',
          'Najwięcej witamin znajduje się tuż pod skórką jabłka.',
          'W Polsce uprawia się ponad 60 odmian jabłoni.',
          'Jabłka unoszą się na wodzie, bo w 25% składają się z powietrza.',
          'Popularne powiedzenie mówi, że jedno jabłko dziennie trzyma lekarza z daleka.',
          'Z jabłek produkuje się cydr, musy i susz na kompoty.',
          'Drzewa jabłoni kwitną na różowo-biało, przyciągając pszczoły.',
          'Jabłka najlepiej przechowywać w chłodnym, ciemnym miejscu.',
          'Odmiany zimowe potrafią leżeć kilka miesięcy bez utraty smaku.',
          'Jabłkowe pestki zawierają śladowe ilości amigdaliny.',
        ],
      },
      {
        image: require('./fruits/banana.png'),
        description: 'Banan',
        facts: [
          'Banany dojrzewają szybciej w obecności innych owoców wydzielających etylen.',
          'Zawierają potas, który wspiera prawidłową pracę mięśni.',
          'Na świecie istnieje ponad 1000 odmian bananów.',
          'Banany rosną na roślinach przypominających drzewa, choć to wielkie zioła.',
          'Skórka banana ciemnieje, gdy owoce są narażone na chłód.',
          'Banany naturalnie rosną w kiściach zwanych rękami.',
          'Niedojrzałe banany są zielone i bogate w skrobię oporną.',
          'Zgniecione banany często dodaje się do wypieków jako naturalny słodzik.',
          'Transport bananów odbywa się w chłodniach, aby spowolnić dojrzewanie.',
          'W kulturach tropikalnych liście bananowca służą jako naturalne talerze.',
        ],
      },
      {
        image: require('./fruits/cherry.png'),
        description: 'Wiśnia',
        facts: [
          'Wiśnie są bogate w antocyjany nadające im czerwony kolor.',
          'Sok z wiśni bywa stosowany jako naturalne wsparcie przy zasypianiu.',
          'Wiśnie kwitną wiosną, przyciągając wiele owadów zapylających.',
          'Pestki wiśni zawierają amigdalinę i nie powinno się ich rozgryzać.',
          'W Polsce popularne są wiśnie łutówki używane do przetworów.',
          'Wiśnie mają niższy poziom cukru niż czereśnie, dlatego są bardziej kwaśne.',
          'Przetwory z wiśni zachowują intensywny kolor dzięki antocyjanom.',
          'Wiśniowe pestki używane są do produkcji naturalnych poduszek grzewczych.',
          'Wiśnia jest często składnikiem deserów takich jak serniki i pierogi.',
          'W sadach wiśniowych stosuje się budki lęgowe dla ptaków zjadających szkodniki.',
        ],
      },
      {
        image: require('./fruits/grape.png'),
        description: 'Winogrono',
        facts: [
          'Winogrona rosną w gronach na pnączu zwanym winoroślą.',
          'Zawierają resweratrol, antyoksydant wspierający serce.',
          'Winogrona mogą być przeznaczone na wino, sok lub spożycie na świeżo.',
          'Skórka ciemnych odmian ma więcej błonnika i barwników niż jasne.',
          'Z suszonych winogron powstają rodzynki bogate w cukry i minerały.',
          'Winogrona dzieli się na odmiany stołowe i winne.',
          'Pestki winogron zawierają olej o właściwościach kosmetycznych.',
          'Z liści winogron przygotowuje się tradycyjne gołąbki dolma.',
          'Winorośl wymaga podpór i regularnego przycinania.',
          'Do fermentacji wina używa się przede wszystkim cukrów z miąższu winogron.',
        ],
      },
      {
        image: require('./fruits/lemon.png'),
        description: 'Cytryna',
        facts: [
          'Cytryny są bogate w witaminę C wzmacniającą odporność.',
          'Sok z cytryny ma kwaśny smak przez obecność kwasu cytrynowego.',
          'Cytryny dojrzewają na zimozielonych drzewach przez cały rok.',
          'Skórka cytryny zawiera aromatyczne olejki eteryczne.',
          'Dodanie cytryny do potraw pomaga zachować jasny kolor owoców i warzyw.',
          'Cytryna dojrzewa około 6-9 miesięcy od pojawienia się kwiatów.',
          'Dodanie soku z cytryny do herbaty nadaje jej orzeźwiający smak.',
          'Skórka cytrynowa bywa używana jako naturalny odświeżacz powietrza.',
          'Cytryny pomagają zapobiegać brunatnieniu krojonych owoców.',
          'Drzewka cytrynowe można hodować w doniczkach w domowych warunkach.',
        ],
      },
      {
        image: require('./fruits/orange.png'),
        description: 'Pomarańcza',
        facts: [
          'Pomarańcze należą do rodziny cytrusów i są mieszańcami mandarynki i pomelo.',
          'Miąższ pomarańczy dzieli się na segmenty wypełnione sokiem.',
          'Pomarańcze zbiera się ręcznie, aby nie uszkodzić delikatnej skórki.',
          'Skórka pomarańczy jest źródłem kandyzowanej skórki i olejków.',
          'Picie soku z pomarańczy rano dostarcza energii i witaminy C.',
          'Pomarańcze zbiera się głównie zimą, kiedy osiągają pełną słodycz.',
          'Miąższ pomarańczy jest bogaty w błonnik pokarmowy.',
          'Skórka pomarańczy zawiera goryczkę, dlatego często się ją blanszuje.',
          'Pomarańczowy olejek eteryczny stosuje się w aromaterapii.',
          'Pomarańcze są częstym dodatkiem do sałatek i dań z drobiu.',
        ],
      },
      {
        image: require('./fruits/pear.png'),
        description: 'Gruszka',
        facts: [
          'Gruszki są miękkie i soczyste dzięki wysokiej zawartości wody.',
          'Najlepiej dojrzewają poza drzewem, w temperaturze pokojowej.',
          'Zawierają błonnik, który sprzyja trawieniu.',
          'Gruszki mają charakterystyczny gruboziarnisty miąższ.',
          'W kuchni używa się ich do deserów, kompotów oraz sałatek.',
          'Gruszki dojrzewają od środka na zewnątrz, dlatego powinno się je delikatnie naciskać przy ogonku.',
          'Istnieją odmiany gruszek przeznaczone do przetworów i do jedzenia na surowo.',
          'Gruszki świetnie komponują się z serami pleśniowymi.',
          'W dawnych czasach gruszki suszono w piecach chlebowych jako zimowy zapas.',
          'Drzewa grusz wytwarzają biały kwiatostan, który przyciąga pszczoły.',
        ],
      },
      {
        image: require('./fruits/pineapple.png'),
        description: 'Ananas',
        facts: [
          'Ananas jest owocem złożonym z wielu małych jagód zrośniętych razem.',
          'Zawiera bromelinę, enzym wspomagający trawienie białek.',
          'Roślina ananasa kwitnie tylko raz, a owoc dojrzewa przez kilka miesięcy.',
          'Ananasy rosną blisko ziemi na niskich roślinach.',
          'Świeży ananas jest gotowy do jedzenia, gdy jego zapach jest słodki i intensywny.',
          'Ananasowe łodygi zawierają włókna używane do produkcji filipińskiej tkaniny pina.',
          'Owoc dojrzewa od środka, dlatego spód bywa słodszy niż wierzch.',
          'Ananasa najlepiej przechowywać w temperaturze pokojowej, aż dojrzeje.',
          'Po zbiorze roślina wypuszcza odrosty, z których można wyhodować nowe okazy.',
          'Z ananasa przygotowuje się sok, konfitury oraz popularne desery lodowe.',
        ],
      },
      {
        image: require('./fruits/strawberry.png'),
        description: 'Truskawka',
        facts: [
          'Truskawka to w botanice owoc pozorny, a jej pestki to orzeszki.',
          'Bogate w witaminę C truskawki wzmacniają odporność organizmu.',
          'Truskawki najlepiej smakują w sezonie wczesnoletnim.',
          'Rośliny truskawki rozmnażają się przez rozłogi zwane wąsami.',
          'Truskawki warto płukać tuż przed jedzeniem, aby nie nasiąkły wodą.',
          'Truskawki są wrażliwe na mróz i wymagają okrywania zimą.',
          'Dobrze rosną w glebie bogatej w kompost i próchnicę.',
          'Truskawki często zapyla się ręcznie w szklarniach, aby zwiększyć plon.',
          'Z truskawek powstają dżemy, syropy oraz mrożone koktajle.',
          'Liście truskawek można suszyć i parzyć jak herbatę.',
        ],
      },
      {
        image: require('./fruits/watermelon.png'),
        description: 'Arbuz',
        facts: [
          'Arbuz składa się w ponad 90% z wody, świetnie nawadnia organizm.',
          'Miąższ arbuza zawiera likopen, czerwony antyoksydant.',
          'Arbuzy wywodzą się z Afryki i lubią ciepły klimat.',
          'Pestki arbuza są jadalne i zawierają zdrowe tłuszcze.',
          'Do sprawdzenia dojrzałości arbuza często używa się opukiwania owocu.',
          'Arbuzy mają liczne odmiany bezpestkowe o słodkim smaku.',
          'Skórka arbuza może służyć do przygotowania kandyzowanych przetworów.',
          'Arbuzy najlepiej rosną na żyznej, piaszczystej glebie o dobrym drenażu.',
          'Owoce dojrzewają około 80 dni po posadzeniu sadzonek.',
          'Arbuz zawiera aminokwas cytrulinę wspierający pracę naczyń krwionośnych.',
        ],
      },
    ],
  },
  {
    title: 'Flagi 1',
    images: [
      {
        image: require('./flags1/poland.png'),
        description: 'Polska',
        facts: [
          'Stolicą Polski jest Warszawa.',
          'Najdłuższą rzeką Polski jest Wisła.',
          'Polska graniczy z siedmioma państwami Europy.',
          'W Polsce obowiązuje waluta złoty.',
          'Najwyższym szczytem Polski są Rysy w Tatrach.',
          'Polska należy do Unii Europejskiej od 2004 roku.',
          'Konstytucja 3 maja była jedną z pierwszych na świecie.',
          'Tradycyjnym polskim daniem są pierogi.',
          'Na liście UNESCO znajduje się historyczna kopalnia soli w Wieliczce.',
          'Polski hymn państwowy to Mazurek Dąbrowskiego.',
        ],
      },
      {
        image: require('./flags1/germany.png'),
        description: 'Niemcy',
        facts: [
          'Stolicą Niemiec jest Berlin.',
          'Niemcy składają się z szesnastu krajów związkowych.',
          'Najdłuższą rzeką Niemiec jest Ren.',
          'Niemcy są największą gospodarką Europy.',
          'Oktoberfest to najsłynniejsze niemieckie święto piwa.',
          'Niemcy są ojczyzną kompozytorów takich jak Bach i Beethoven.',
          'Autostrady w Niemczech znane są z odcinków bez ograniczeń prędkości.',
          'Niemcy były współzałożycielami Unii Europejskiej.',
          'W Bawarii leży zamek Neuschwanstein inspirowany baśniami.',
          'Niemiecka kuchnia słynie z kiełbas, precli i kapusty kiszonej.',
        ],
      },
      {
        image: require('./flags1/france.png'),
        description: 'Francja',
        facts: [
          'Stolicą Francji jest Paryż.',
          'Wieża Eiffla została zbudowana w 1889 roku.',
          'Francja jest największym krajem Unii Europejskiej pod względem powierzchni.',
          'Francuska kuchnia słynie z bagietek, serów i wina.',
          'Luwr to najczęściej odwiedzane muzeum na świecie.',
          'Francja posiada departamenty i terytoria zamorskie.',
          'Rewolucja Francuska rozpoczęła się w 1789 roku.',
          'Narodowe motto Francji brzmi Wolność, Równość, Braterstwo.',
          'Francja jest jednym z największych producentów wina na świecie.',
          'Oficjalną walutą Francji jest euro.',
        ],
      },
      {
        image: require('./flags1/spain.png'),
        description: 'Hiszpania',
        facts: [
          'Stolicą Hiszpanii jest Madryt.',
          'Hiszpania składa się z siedemnastu wspólnot autonomicznych.',
          'Językiem urzędowym jest hiszpański, a istnieją też języki regionalne.',
          'Słynne święto La Tomatina odbywa się w Buñol.',
          'Hiszpania posiada terytoria na Morzu Śródziemnym i Atlantyku.',
          'Sagrada Família to dzieło Antoniego Gaudiego w Barcelonie.',
          'Hiszpania jest jednym z największych producentów oliwy z oliwek.',
          'Na Wyspach Kanaryjskich znajduje się wulkan Teide.',
          'Flamenco pochodzi z Andaluzji.',
          'W Pampelunie odbywa się bieg byków podczas San Fermín.',
        ],
      },
      {
        image: require('./flags1/italy.png'),
        description: 'Włochy',
        facts: [
          'Stolicą Włoch jest Rzym.',
          'Włochy na mapie przypominają but.',
          'W Rzymie znajduje się państwo Watykan.',
          'Włoska kuchnia słynie z makaronów, pizzy i espresso.',
          'Włochy mają najwięcej obiektów UNESCO na świecie.',
          'Renesans narodził się we Florencji.',
          'Najwyższym szczytem Włoch jest Mont Blanc na granicy z Francją.',
          'Włochy otaczają morza Adriatyckie, Tyrreńskie, Jońskie i Liguryjskie.',
          'Alpy i Apeniny tworzą główne pasma górskie Włoch.',
          'Marki Ferrari i Lamborghini pochodzą z Włoch.',
        ],
      },
      {
        image: require('./flags1/portugal.png'),
        description: 'Portugalia',
        facts: [
          'Stolicą Portugalii jest Lizbona.',
          'Cabo da Roca to najbardziej wysunięty na zachód punkt Europy kontynentalnej.',
          'Portugalia była potęgą morską w epoce wielkich odkryć.',
          'Język portugalski jest językiem urzędowym w wielu krajach na świecie.',
          'Słynne wino porto pochodzi z doliny Douro.',
          'Muzyka fado wywodzi się z Lizbony i Coimbry.',
          'Portugalia dzieli Półwysep Iberyjski tylko z Hiszpanią.',
          'Wyspy Azory i Madera są autonomicznymi regionami Portugalii.',
          'Pastéis de nata to popularne portugalskie ciastka.',
          'Portugalia ma łagodny klimat i liczne plaże nad Atlantykiem.',
        ],
      },
      {
        image: require('./flags1/sweden.png'),
        description: 'Szwecja',
        facts: [
          'Stolicą Szwecji jest Sztokholm.',
          'Szwecja leży na Półwyspie Skandynawskim.',
          'Kraj słynie z tysięcy jezior i rozległych lasów.',
          'Szwecja jest monarchią konstytucyjną.',
          'Sieć sklepów IKEA powstała w Szwecji.',
          'Szwecja ma rozbudowany system opieki społecznej.',
          'Święto Midsommar to ważna tradycja w Szwecji.',
          'Szwecja jest ojczyzną zespołu ABBA.',
          'Nagrody Nobla przyznawane są w Sztokholmie przez szwedzkie instytucje.',
          'Oficjalną walutą Szwecji jest korona szwedzka.',
        ],
      },
      {
        image: require('./flags1/norway.png'),
        description: 'Norwegia',
        facts: [
          'Stolicą Norwegii jest Oslo.',
          'Norwegia słynie z głębokich fiordów.',
          'Kraj nie należy do Unii Europejskiej, ale jest w Europejskim Obszarze Gospodarczym.',
          'Norwegia bogaci się na wydobyciu ropy naftowej i gazu.',
          'Norwegia obejmuje arktyczny archipelag Svalbard.',
          'W Norwegii często można zobaczyć zorzę polarną.',
          'Norwegowie świętują dzień konstytucji 17 maja.',
          'Norwegia jest monarchią dziedziczną.',
          'Tradycyjnym przysmakiem jest suszona ryba stockfish i wędzony łosoś.',
          'Norwegia należy do krajów o najwyższej jakości życia.',
        ],
      },
      {
        image: require('./flags1/finland.png'),
        description: 'Finlandia',
        facts: [
          'Stolicą Finlandii jest Helsinki.',
          'Finlandia słynie z tysięcy jezior i lasów.',
          'Państwo graniczy z Rosją, Szwecją i Norwegią.',
          'Fiński system edukacji uchodzi za jeden z najlepszych na świecie.',
          'Oficjalnymi językami są fiński i szwedzki.',
          'Finowie uwielbiają sauny i mają ich najwięcej na mieszkańca.',
          'Firma Nokia wywodzi się z Finlandii.',
          'Finlandia należy do strefy euro od 2002 roku.',
          'W Laponii działa wioska Świętego Mikołaja.',
          'Finlandia produkuje energię głównie z czystych źródeł.',
        ],
      },
      {
        image: require('./flags1/denmark.png'),
        description: 'Dania',
        facts: [
          'Stolicą Danii jest Kopenhaga.',
          'Dania leży na Półwyspie Jutlandzkim i licznych wyspach.',
          'Królestwo Danii obejmuje Grenlandię i Wyspy Owcze.',
          'Duńczycy cenią koncepcję hygge, czyli przytulnego stylu życia.',
          'Dania jest członkiem Unii Europejskiej od 1973 roku.',
          'Most Øresund łączy Danię ze Szwecją.',
          'Smørrebrød to tradycyjne duńskie kanapki.',
          'Klocki Lego wynaleziono w duńskim Billund.',
          'Dania inwestuje w energetykę wiatrową.',
          'W Kopenhadze popularnym środkiem transportu jest rower.',
        ],
      },
    ],
  },
  {
    title: 'Flagi 2',
    images: [
      {
        image: require('./flags2/czechia.png'),
        description: 'Czechy',
        facts: [
          'Stolicą Czech jest Praga.',
          'Czechy słyną z zamku na Hradczanach.',
          'Najdłuższą rzeką Czech jest Wełtawa.',
          'Czechy znane są z warzenia piwa, szczególnie w Pilznie.',
          'Kraj graniczy z Polską, Niemcami, Austrią i Słowacją.',
          'Język czeski należy do rodziny języków słowiańskich.',
          'Czechy są członkiem Unii Europejskiej i strefy Schengen.',
          'Karlowe Wary to znane uzdrowisko w Czechach.',
          'Marka samochodów Škoda powstała w Czechach.',
          'Czeska flaga ma niebieski trójkąt oraz pasy białe i czerwone.',
        ],
      },
      {
        image: require('./flags2/slovakia.png'),
        description: 'Słowacja',
        facts: [
          'Stolicą Słowacji jest Bratysława.',
          'Słowacja ma liczne zamki w dolinie rzeki Wag.',
          'Najwyższym pasmem Słowacji są Tatry Wysokie.',
          'Słowacja graniczy z Polską, Czechami, Austrią, Węgrami i Ukrainą.',
          'Oficjalną walutą Słowacji jest euro.',
          'Językiem urzędowym Słowacji jest język słowacki.',
          'Słowacja znana jest z jaskiń krasowych wpisanych na listę UNESCO.',
          'Bratysława graniczy jednocześnie z Austrią i Węgrami.',
          'Słowackie stroje ludowe noszone są podczas festynów góralskich.',
          'Słowacja powstała jako niezależne państwo w 1993 roku.',
        ],
      },
      {
        image: require('./flags2/hungary.png'),
        description: 'Węgry',
        facts: [
          'Stolicą Węgier jest Budapeszt.',
          'Przez Budapeszt przepływa Dunaj dzielący Budę i Peszt.',
          'Oficjalną walutą Węgier jest forint.',
          'Węgry słyną z wód termalnych i licznych łaźni.',
          'Papryka jest podstawową przyprawą kuchni węgierskiej.',
          'Jezioro Balaton to największy akwen Europy Środkowej.',
          'Węgry mają bogate tradycje muzyki cygańskiej i tańca csárdás.',
          'Węgry są członkiem Unii Europejskiej od 2004 roku.',
          'Węgierska Puszta to rozległe stepowe równiny.',
          'Festiwal Sziget odbywa się na wyspie Óbuda w Budapeszcie.',
        ],
      },
      {
        image: require('./flags2/romania.png'),
        description: 'Rumunia',
        facts: [
          'Stolicą Rumunii jest Bukareszt.',
          'Transylwania słynie z zamków i legendy o Drakuli.',
          'Karpaty zajmują znaczną część terytorium Rumunii.',
          'Oficjalną walutą Rumunii jest lej.',
          'Dunaj tworzy deltę będącą rezerwatem biosfery UNESCO.',
          'Rumunia ma dostęp do Morza Czarnego.',
          'Tradycyjnym daniem Rumunii jest sarmale z kiszonej kapusty.',
          'Rumunia należy do Unii Europejskiej od 2007 roku.',
          'W Rumunii znajduje się malowany klasztor Voroneț.',
          'Język rumuński należy do rodziny języków romańskich.',
        ],
      },
      {
        image: require('./flags2/bulgaria.png'),
        description: 'Bułgaria',
        facts: [
          'Stolicą Bułgarii jest Sofia.',
          'Bułgaria leży nad Morzem Czarnym.',
          'Oficjalną walutą Bułgarii jest lew.',
          'Dolina Róż słynie z produkcji olejku różanego.',
          'Góry Riła i Piryn przyciągają miłośników turystyki górskiej.',
          'Bułgaria jest jednym z najstarszych państw w Europie.',
          'Szopska sałatka to tradycyjne bułgarskie danie.',
          'Bułgaria ma liczne cerkwie i klasztory prawosławne.',
          'Bułgaria wstąpiła do Unii Europejskiej w 2007 roku.',
          'Zwyczaj Martenicy polega na noszeniu czerwono-białych bransoletek.',
        ],
      },
      {
        image: require('./flags2/greece.png'),
        description: 'Grecja',
        facts: [
          'Stolicą Grecji są Ateny.',
          'Grecja uznawana jest za kolebkę demokracji.',
          'Greckie wyspy stanowią znaczną część kraju.',
          'Grecja leży nad Morzem Egejskim, Jońskim i Śródziemnym.',
          'Kuchnia grecka obfituje w oliwę, fetę i oliwki.',
          'Na Akropolu w Atenach stoi świątynia Partenon.',
          'Grecja posługuje się walutą euro.',
          'Grecja należy do Unii Europejskiej od 1981 roku.',
          'Starożytne Igrzyska Olimpijskie narodziły się w Olimpii.',
          'Językiem urzędowym Grecji jest grecki.',
        ],
      },
      {
        image: require('./flags2/croatia.png'),
        description: 'Chorwacja',
        facts: [
          'Stolicą Chorwacji jest Zagrzeb.',
          'Chorwacja ma długą linię brzegową nad Adriatykiem.',
          'Dubrownik nosi miano Perły Adriatyku.',
          'Chorwacja posiada ponad tysiąc wysp i wysepek.',
          'Park Narodowy Plitwickie Jeziora słynie z turkusowych wodospadów.',
          'Chorwacja wprowadziła euro jako walutę w 2023 roku.',
          'Reprezentacja Chorwacji odnosi sukcesy w piłce nożnej.',
          'Chorwacja należy do Unii Europejskiej od 2013 roku.',
          'Danie peka piecze się pod ciężką żeliwną pokrywą.',
          'Językiem urzędowym Chorwacji jest chorwacki.',
        ],
      },
      {
        image: require('./flags2/slovenia.png'),
        description: 'Słowenia',
        facts: [
          'Stolicą Słowenii jest Lublana.',
          'Słowenia leży na styku Alp i Adriatyku.',
          'Walutą Słowenii jest euro.',
          'Jaskinia Postojna to słynny system krasowy.',
          'Słowenia ma krótki dostęp do Morza Adriatyckiego.',
          'Językiem urzędowym jest język słoweński.',
          'Jezioro Bled słynie z wyspy z kościołem.',
          'Około 60 procent powierzchni kraju pokrywają lasy.',
          'Słowenia należy do Unii Europejskiej i strefy Schengen.',
          'Tradycyjną potrawą jest potica i kranjska kiełbasa.',
        ],
      },
      {
        image: require('./flags2/lithuana.png'),
        description: 'Litwa',
        facts: [
          'Stolicą Litwy jest Wilno.',
          'Litwa leży nad Morzem Bałtyckim.',
          'Litwa przyjęła euro w 2015 roku.',
          'Litwa i Polska tworzyły niegdyś Rzeczpospolitą Obojga Narodów.',
          'Język litewski należy do najstarszych języków indoeuropejskich.',
          'Ostra Brama w Wilnie jest ważnym sanktuarium.',
          'Litwa jest członkiem NATO i Unii Europejskiej.',
          'Mierzeja Kurońska wpisana jest na listę UNESCO.',
          'Koszykówka uważana jest na Litwie za sport narodowy.',
          'Litwa odzyskała niepodległość w 1990 roku.',
        ],
      },
      {
        image: require('./flags2/lativa.png'),
        description: 'Łotwa',
        facts: [
          'Stolicą Łotwy jest Ryga.',
          'Łotwa leży nad Morzem Bałtyckim.',
          'Łotwa wprowadziła euro w 2014 roku.',
          'Językiem urzędowym Łotwy jest język łotewski.',
          'Ryga słynie z architektury w stylu secesji.',
          'Duża część Łotwy pokryta jest lasami i torfowiskami.',
          'Dzień Niepodległości Łotwy obchodzony jest 18 listopada.',
          'Łotwa jest członkiem NATO i Unii Europejskiej.',
          'Tradycyjne łotewskie pasy Lielvārde zdobią stroje ludowe.',
          'Hokej na lodzie cieszy się na Łotwie wielką popularnością.',
        ],
      },
    ],
  },
];
